name: the flight
favicon: null
layout_spectrum: 0.06468648393638432
typography_spectrum: 0.24072749563492835
title: The Flight Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#494949'
    - '#8a8a8a'
    - '#b9b9b9'
    - '#6b6b6b'
  brandStrength: 0.24728438071906567
  lightness: 0.5955923807341605
  saturation: 0.3944513953756541
  rhythmicContrast: 0.9115997951012105
purpose: []
